
# Project information
site_name: 'C++ Tutorials'
site_description: 'A tutorial to c++'
site_author: 'San Diego Code'
site_url: 'https://sdcoding.com/c++'

pages:
- Home: index.md
#- PAGE NAME:  file.md

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/sandiegocode/c++'

# Copyright
copyright: © San Diego Code

# Documentation and theme
theme: 'material'

# Options
extra:
  palette:
    primary: 'purple'
    accent: 'light blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  i18n:
    prev: 'Previous'
    next: 'Next'
  author:
    github: 'sandiegocode'


# Extensions
markdown_extensions:
  - admonition

#Compiler Code
extra_css: [compiler.css]
extra_javascript: [compiler.js]
